// let obj1={
//     name:"aravind",
//     age:25,
//     greet:function(){
//         return `Hello this is ${this.name}`
//     }

// }

// let obj2={
//     name:"babu",
//     age:30,
//     education:"bsc",
//     greet:function(){
//         return `Hello my name is ${this.name}`
//     }
// }
// let merge=Object.assign({},obj1,obj2);
// console.log(merge);


// let obj={
//     name:"ARAVIND"
// }
// Object.freeze(obj);